name: Qv2ray build debian package - multiarch

on:
  push:
  release:
    types: [prereleased]

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64v8, mips64le]
    needs: check_commit_msg
    if: ${{ !contains( needs.check_commit_msg.outputs.commit_message, 'NO_DEB') }}
    name: Debian
    runs-on: ubuntu-latest

    steps:
      - name: setup qemu
        run: |
          sudo apt-get install -y qemu qemu-user-static
      - name: setup container
        uses: docker://${{ matrix.arch }}/debian:stable
      - name: test
        run: |
          lsb_release -a
