name: Qv2ray build debian package - multiarch

on:
  push:
  release:
    types: [prereleased]

jobs:

  linux:
    name: Debian
    runs-on: ubuntu-latest

    steps:
      - name: setup qemu
        run: |
          sudo apt-get install -y qemu qemu-user-static
      - name: setup container
        uses: docker://arm64v8/debian:stable
      - name: test
        run: |
          lsb_release -a
